// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDKJ.Models
{
    public partial class Tbgrupa
    {
        public Tbgrupa()
        {
            Tbtowar = new HashSet<Tbtowar>();
        }

        public int Idgrupa { get; set; }
        public string NazwaGrupa { get; set; }
        public string SymbolGrupa { get; set; }

        public virtual ICollection<Tbtowar> Tbtowar { get; set; }
    }
}