// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDKJ.Models
{
    public partial class Tbtowar
    {
        public int Idtowar { get; set; }
        public string Nazwa { get; set; }
        public string Indeks { get; set; }
        public string Ean { get; set; }
        public int? Fjm { get; set; }
        public int? Pozycja { get; set; }
        public int? Fgrupa { get; set; }
        public string Opis { get; set; }
        public int? Ilosciowa { get; set; }

        public virtual Tbgrupa FgrupaNavigation { get; set; }
        public virtual Tbjm FjmNavigation { get; set; }
    }
}