// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BlazorDKJ.Models;

namespace BlazorDKJ.Data
{
    public partial class mczeContext : DbContext
    {
        public mczeContext()
        {
        }

        public mczeContext(DbContextOptions<mczeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Tbgrupa> Tbgrupa { get; set; }
        public virtual DbSet<Tbjm> Tbjm { get; set; }
        public virtual DbSet<Tbtowar> Tbtowar { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tbgrupa>(entity =>
            {
                entity.HasKey(e => e.Idgrupa)
                    .HasName("PK_tbgrupa_idgrupa");

                entity.ToTable("tbgrupa", "mcze");

                entity.Property(e => e.Idgrupa).HasColumnName("idgrupa");

                entity.Property(e => e.NazwaGrupa)
                    .HasMaxLength(45)
                    .HasColumnName("Nazwa_grupa");

                entity.Property(e => e.SymbolGrupa)
                    .HasMaxLength(15)
                    .HasColumnName("Symbol_grupa");
            });

            modelBuilder.Entity<Tbjm>(entity =>
            {
                entity.HasKey(e => e.Idjm)
                    .HasName("PK_tbjm_IDJm");

                entity.ToTable("tbjm", "mcze");

                entity.Property(e => e.Idjm).HasColumnName("IDJm");

                entity.Property(e => e.Jm).HasMaxLength(5);

                entity.Property(e => e.Opis).HasMaxLength(25);
            });

            modelBuilder.Entity<Tbtowar>(entity =>
            {
                entity.HasKey(e => e.Idtowar)
                    .HasName("PK_tbtowar_IDTowar");

                entity.ToTable("tbtowar", "mcze");

                entity.HasIndex(e => e.Fgrupa, "FGrupa_idx");

                entity.HasIndex(e => e.Fjm, "FJm_idx");

                entity.Property(e => e.Idtowar).HasColumnName("IDTowar");

                entity.Property(e => e.Ean).HasMaxLength(45);

                entity.Property(e => e.Fgrupa).HasColumnName("FGrupa");

                entity.Property(e => e.Fjm).HasColumnName("FJm");

                entity.Property(e => e.Indeks).HasMaxLength(45);

                entity.Property(e => e.Nazwa).HasMaxLength(65);

                entity.Property(e => e.Opis).HasMaxLength(45);

                entity.HasOne(d => d.FgrupaNavigation)
                    .WithMany(p => p.Tbtowar)
                    .HasForeignKey(d => d.Fgrupa)
                    .HasConstraintName("tbtowar$FGrupa");

                entity.HasOne(d => d.FjmNavigation)
                    .WithMany(p => p.Tbtowar)
                    .HasForeignKey(d => d.Fjm)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("tbtowar$FJm");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}